export const TEMPLATE_ALPHA = {
  faint: "20",
  soft: "40",
  medium: "55",
};

export const TERMINAL_TEMPLATE_FONTS = {
  body: "'DM Sans', system-ui, sans-serif",
  display: "'Space Mono', 'IBM Plex Mono', monospace",
  mono: "'Space Mono', 'IBM Plex Mono', monospace",
};

export const TERMINAL_TEMPLATE_COLORS = {
  avatarBackground: "#0b0b0b",
  bodyText: "#d4d4d4",
  commandText: "#f8fafc",
  cursor: "#d1d5db",
  educationInstitution: "#93c5fd",
  experienceCompany: "#60a5fa",
  experienceRole: "#facc15",
  lineText: "#e5e7eb",
  muted: "#6b7280",
  pageBackground: "#050505",
  prompt: "#4ade80",
  shellBackground: "#111111",
  shellBorder: "#252525",
  skillChipBackground: "#161616",
  skillTrack: "#202020",
  topBorder: "#232323",
  trafficGreen: "#22c55e",
  trafficRed: "#ef4444",
  trafficYellow: "#f59e0b",
  primaryName: "#60a5fa",
  secondaryText: "#9ca3af",
};

export const TERMINAL_TEMPLATE_LAYOUT = {
  avatarSize: 108,
  iconSize: 14,
  iconStrokeWidth: 2.1,
  pageMinHeight: 900,
  pagePadding: 18,
  shellBorderRadius: 24,
  shellPadding: "18px 22px 26px",
};

export const TERMINAL_TEMPLATE_TYPOGRAPHY = {
  bodySize: 13,
  cursorFontSize: 12,
  educationBodySize: 12.5,
  educationMetaSize: 12,
  educationTitleSize: 13,
  experienceBodySize: 13,
  experienceMetaSize: 11,
  experienceTitleSize: 14,
  headerSize: 11,
  nameLineHeight: 1.1,
  nameSizeMultiplier: 1.62,
  promptSize: 12,
  skillPercentSize: 11,
  skillTextSize: 12,
  summaryLineHeight: 1.78,
};

export const TERMINAL_SKILL_COMMANDS = {
  bars: "./skills --view=bars",
  chips: "printf \"%s\\n\" $SKILLS",
  radar: "./skills --view=radar",
};

export const TERMINAL_EXPORT_CURSOR_ANIMATION = "none";
export const TERMINAL_PREVIEW_CURSOR_ANIMATION = "pulse 1.2s ease-in-out infinite";

export const DASHBOARD_TEMPLATE_FONTS = {
  body: "'DM Sans', system-ui, sans-serif",
  display: "'DM Sans', system-ui, sans-serif",
  mono: "'Space Mono', 'IBM Plex Mono', monospace",
};

export const DASHBOARD_TEMPLATE_COLORS = {
  badgeBackground: "#111827",
  badgeBorder: "#1f2937",
  bodyText: "#e2e8f0",
  cardBackground: "#0b1120",
  cardBorder: "#1e293b",
  headingPrimary: "#67e8f9",
  headingSecondary: "#94a3b8",
  muted: "#64748b",
  nestedCardBackground: "#0f172a",
  pageBackground: "#020617",
  photoBackground: "#0f172a",
  radarGrid: "#334155",
  secondaryText: "#cbd5e1",
  strongText: "#f8fafc",
};

export const DASHBOARD_TEMPLATE_LAYOUT = {
  cardBorderRadius: 22,
  cardPadding: 22,
  contactGap: 8,
  contactIconSize: 14,
  contactIconStrokeWidth: 2.2,
  contactLineGap: 10,
  dashboardGap: 18,
  dashboardGridColumns: "minmax(0, 1.28fr) minmax(280px, 0.92fr)",
  educationGap: 12,
  educationHeaderMarginBottom: 2,
  educationItemPaddingTop: 12,
  entryGap: 12,
  experienceCardBorderRadius: 18,
  experienceCardPadding: 16,
  experienceHeaderGap: 16,
  experienceHeaderMarginBottom: 8,
  headerGap: 24,
  headerMarginBottom: 18,
  headerMetaContactOnlyWidth: 240,
  headerMetaPhotoContactWidth: 320,
  headerMetaPhotoOnlyWidth: 92,
  iconSize: 16,
  iconStrokeWidth: 2.1,
  languageBlockMarginBottom: 18,
  languageGap: 9,
  metaMarginTop: 4,
  pageMinHeight: 900,
  pagePadding: 24,
  pillRadius: 999,
  periodBadgePadding: "6px 10px",
  periodBadgeRadius: 999,
  photoGridGap: 16,
  photoGridPhotoOnlyColumns: "92px",
  photoGridWithContactColumns: "92px minmax(0, 1fr)",
  photoHeight: 112,
  photoShadow: "0 14px 30px rgba(2, 6, 23, 0.32)",
  photoWidth: 92,
  radarCenter: "50%",
  radarExportHeight: 230,
  radarExportWidth: 290,
  radarFillOpacity: 0.22,
  radarMinHeight: 230,
  radarOuterRadius: "68%",
  radarStrokeWidth: 2.2,
  radarTooltipBorderRadius: 12,
  skillCardHeadingMarginBottom: 8,
  skillLevelGap: 11,
  skillLevelHeaderMarginBottom: 5,
  skillTrackHeight: 4,
  textBlockMarginTop: 8,
  titleMarginTop: 8,
};

export const DASHBOARD_TEMPLATE_TYPOGRAPHY = {
  baseSize: 13,
  descriptionLineHeight: 1.75,
  descriptionSize: 13,
  educationDetailsLineHeight: 1.7,
  educationDetailsSize: 12,
  educationDegreeSize: 15,
  educationMetaSize: 12,
  experienceCompanySize: 13,
  experienceRoleSize: 17,
  headingLetterSpacing: "0.18em",
  headingMarginBottom: 14,
  headingSize: 11,
  headingWeight: 700,
  hobbiesLineHeight: 1.75,
  hobbiesSize: 13,
  languageLevelSize: 10,
  languageNameSize: 13,
  languageNameWeight: 600,
  nameLetterSpacing: "-0.03em",
  nameLineHeight: 0.96,
  nameSizeMultiplier: 2.7,
  nameWeight: 800,
  periodSize: 10,
  periodWeight: 700,
  radarLabelSize: 10,
  radarTooltipSize: 11,
  sectionTitleWeight: 700,
  sectionMetaWeight: 600,
  skillLabelSize: 12,
  skillValueSize: 11,
  summaryLineHeight: 1.8,
  summarySize: 14,
  titleSizeMultiplier: 1.05,
};

export const DASHBOARD_RADAR_LIMITS = {
  maxLabelLength: 12,
};

export const DASHBOARD_TEMPLATE_TEXT = {
  educationSeparator: " \u00c2\u00b7 ",
};

export const SHARED_TEMPLATE_COLORS = {
  darkChipBackground: "rgba(255,255,255,0.14)",
  darkChipBorder: "rgba(255,255,255,0.18)",
  darkChipText: "rgba(255,255,255,0.9)",
  darkSkillFill: "rgba(255,255,255,0.75)",
  darkSkillLabel: "rgba(255,255,255,0.85)",
  darkSkillLevel: "rgba(255,255,255,0.45)",
  darkSkillTrack: "rgba(255,255,255,0.12)",
  darkRadarLabel: "rgba(255,255,255,0.7)",
  darkRadarRing: "rgba(255,255,255,0.1)",
  darkRadarShape: "rgba(255,255,255,0.6)",
  lightBody: "#475569",
  lightSkillLabel: "#334155",
  lightSkillLevel: "#94a3b8",
  lightTimelineTitle: "#0f172a",
  sidebarLabel: "rgba(255,255,255,0.42)",
  white: "#ffffff",
};

export const SHARED_TEMPLATE_LAYOUT = {
  photoMaxScale: 3,
  photoMinScale: 1,
  photoPositionMax: 100,
  photoPositionMin: 0,
  radarCenterX: 80,
  radarCenterY: 80,
  radarLabelOffset: 16,
  radarMaxItems: 6,
  radarMaxWidth: 160,
  radarRadius: 60,
  radarViewBox: "0 0 160 160",
  secTitleAccentHeight: 16,
  secTitleAccentRadius: 2,
  secTitleAccentWidth: 3,
  secTitleGap: 10,
  secTitleLineHeight: 1,
  secTitleMarginBottom: 14,
  secTitleMarginTop: 22,
  skillBarGap: 4,
  skillBarMarginBottom: 10,
  skillChipBorderRadius: 20,
  skillChipPadding: "3px 10px",
  skillFallbackGap: 5,
  skillTrackBorderRadius: 4,
  skillTrackHeight: 4,
  timelineBodyLineHeight: 1.65,
  timelineBodyMarginTop: 5,
  timelineContentPaddingBottom: 14,
  timelineDotBorderWidth: 2,
  timelineDotMarginLeft: -5,
  timelineDotSize: 9,
  timelineGap: 14,
  timelineHeaderGap: 4,
  timelineHeaderMarginBottom: 2,
  timelineItemMarginBottom: 20,
  timelineRailMarginTop: 4,
  timelineRailMinHeight: 20,
  timelineRailWidth: 1,
  timelineTrackPaddingTop: 4,
};

export const SHARED_TEMPLATE_TYPOGRAPHY = {
  radarLabelSize: 7.5,
  radarLabelWeight: 600,
  secTitleLetterSpacing: "0.16em",
  secTitleSize: 9,
  secTitleWeight: 700,
  sidebarLabelLetterSpacing: "0.18em",
  sidebarLabelMarginBottom: 10,
  sidebarLabelSize: 9,
  sidebarLabelWeight: 700,
  skillChipLetterSpacing: "0.02em",
  skillChipSize: 10,
  skillChipWeight: 600,
  skillLabelSize: 10,
  skillLabelWeight: 600,
  skillLevelSize: 9,
  timelineBodySizeMultiplier: 0.88,
  timelinePeriodSizeMultiplier: 0.77,
  timelineSubSizeMultiplier: 0.86,
  timelineSubWeight: 600,
  timelineTitleWeight: 700,
};

export const SHARED_RADAR_RINGS = [25, 50, 75, 100];
export const SHARED_TEMPLATE_TEXT = {
  timelineSeparator: " \u00c2\u00b7 ",
};

export const CARD_TEMPLATE_COLORS = {
  contactText: "#64748b",
  divider: "#f1f5f9",
  entryBody: "#64748b",
  muted: "#94a3b8",
  pageBackground: "#f0f4f8",
  panelBackground: "#ffffff",
  primaryText: "#0f172a",
  secondaryText: "#475569",
  subtleBorder: "#f8fafc",
  tagBackground: "#f1f5f9",
};

export const CARD_TEMPLATE_LAYOUT = {
  cardBorderRadius: 10,
  cardMarginBottom: 10,
  cardPadding: "22px 24px",
  cardShadow: "0 1px 3px rgba(0,0,0,0.06),0 4px 14px rgba(0,0,0,0.06)",
  contactDotSize: 3,
  contactGap: "3px 16px",
  contactItemGap: 5,
  gridColumns: "1fr 1fr",
  gridGap: 10,
  headerBorderTopWidth: 4,
  headerGap: 22,
  hobbyGap: 6,
  hobbyPadding: "3px 10px",
  languageDividerPadding: 8,
  pagePadding: 22,
  photoSize: 82,
  sectionAccentBorderRadius: 2,
  sectionAccentHeight: 14,
  sectionAccentWidth: 3,
  sectionGap: 8,
  sectionMarginBottom: 14,
};

export const CARD_TEMPLATE_TYPOGRAPHY = {
  bodyLineHeight: 1.62,
  contactSizeMultiplier: 0.79,
  educationBodyLineHeight: 1.6,
  educationBodySizeMultiplier: 0.83,
  educationTitleSizeMultiplier: 0.9,
  entryMetaSizeMultiplier: 0.83,
  entryPeriodSizeMultiplier: 0.74,
  entryTitleSizeMultiplier: 0.94,
  gradeSizeMultiplier: 0.79,
  hobbySizeMultiplier: 0.79,
  languageLevelSizeMultiplier: 0.77,
  languageNameSizeMultiplier: 0.87,
  nameLetterSpacing: "-0.02em",
  nameLineHeight: 1.1,
  nameSizeMultiplier: 1.95,
  placeholderSize: 26,
  sectionLetterSpacing: "0.16em",
  sectionSize: 9,
  summaryLineHeight: 1.73,
  summarySizeMultiplier: 0.9,
  titleSizeMultiplier: 0.9,
};

export const CARD_TEMPLATE_TEXT = {
  gradePrefix: "\u00c3\u02dc ",
  periodSeparator: "\u00e2\u20ac\u201c",
};
