export const CANVAS_COPY = {
  DE: {
    addTools: {
      ellipse: "() Kreis",
      line: "-- Linie",
      rect: "[] Rechteck",
      text: "T Textfeld",
    },
    appearance: "Aussehen",
    background: "Hintergrund",
    borderColor: "Rahmenfarbe",
    borderRadius: "Eckenradius",
    borderWidth: "Rahmenstaerke",
    canvas: "Arbeitsflaeche",
    delete: "Loeschen",
    deleteHint: "Loeschen (Entf)",
    duplicate: "Duplizieren",
    duplicateHint: "Duplizieren (Strg+D)",
    elements: count => `${count} Elemente`,
    emptySelection: "Kein Element ausgewaehlt",
    exporting: "Export...",
    fillColor: "Fuellfarbe",
    fit: "Anpassung",
    height: "Hoehe",
    image: "Bild",
    imageCropReset: "Bildausschnitt zuruecksetzen",
    layer: z => `Ebene ${z}`,
    layerBack: "Ganz nach hinten",
    layerBackShort: "Bot",
    layerBackward: "Nach hinten",
    layerBackwardHint: "Ebene rueckwaerts",
    layerForward: "Nach vorne",
    layerForwardHint: "Ebene vorwaerts",
    layerFront: "Ganz nach vorne",
    layerFrontShort: "Top",
    layers: "Ebenen",
    lineHeight: "Zeilenabstand",
    locked: "Sperren",
    lockedBadge: "Lock",
    noSelection: "Kein Element ausgewaehlt",
    opacity: "Deckkraft",
    positionSize: "Position & Groesse",
    properties: "Eigenschaften",
    resetTemplate: "Vorlage zuruecksetzen",
    selected: (label, x, y) => `Ausgewaehlt: ${label} @ ${x}, ${y}`,
    shapeOrder: "Ebenenreihenfolge",
    snapActive: "Raster aktiv",
    snapInactive: "Raster inaktiv",
    snapOff: "Raster aus",
    statusHints: "Doppelklick = Bearbeiten | Entf = Loeschen | Pfeiltasten = Bewegen | Strg+D = Duplizieren",
    textColor: "Textfarbe",
    transparent: "Transparent",
    typography: "Typografie",
    unlocked: "Entsperren",
    zoom: "Zoom",
    fontFamily: "Schriftart",
    fontSize: "Groesse",
    horizontal: "Horizontal",
    vertical: "Vertikal",
    width: "Breite",
  },
  EN: {
    addTools: {
      ellipse: "() Circle",
      line: "-- Line",
      rect: "[] Rectangle",
      text: "T Text Box",
    },
    appearance: "Appearance",
    background: "Background",
    borderColor: "Border color",
    borderRadius: "Corner radius",
    borderWidth: "Border width",
    canvas: "Canvas",
    delete: "Delete",
    deleteHint: "Delete (Del)",
    duplicate: "Duplicate",
    duplicateHint: "Duplicate (Ctrl+D)",
    elements: count => `${count} elements`,
    emptySelection: "No element selected",
    exporting: "Exporting...",
    fillColor: "Fill color",
    fit: "Fit",
    height: "Height",
    image: "Image",
    imageCropReset: "Reset image crop",
    layer: z => `Layer ${z}`,
    layerBack: "Send to back",
    layerBackShort: "Back",
    layerBackward: "Send backward",
    layerBackwardHint: "Send layer backward",
    layerForward: "Bring forward",
    layerForwardHint: "Bring layer forward",
    layerFront: "Bring to front",
    layerFrontShort: "Front",
    layers: "Layers",
    lineHeight: "Line height",
    locked: "Lock",
    lockedBadge: "Lock",
    noSelection: "No element selected",
    opacity: "Opacity",
    positionSize: "Position & Size",
    properties: "Properties",
    resetTemplate: "Reset template",
    selected: (label, x, y) => `Selected: ${label} @ ${x}, ${y}`,
    shapeOrder: "Layer order",
    snapActive: "Grid on",
    snapInactive: "Grid inactive",
    snapOff: "Grid off",
    statusHints: "Double-click = Edit | Del = Delete | Arrow keys = Move | Ctrl+D = Duplicate",
    textColor: "Text color",
    transparent: "Transparent",
    typography: "Typography",
    unlocked: "Unlock",
    zoom: "Zoom",
    fontFamily: "Font family",
    fontSize: "Size",
    horizontal: "Horizontal",
    vertical: "Vertical",
    width: "Width",
  },
};
